name: toy_library_mobile
description: Toy Library mobile app
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  provider: ^6.1.2
  supabase_flutter: ^2.9.1
  image_picker: ^1.1.2
  google_maps_flutter: ^2.12.3
  url_launcher: ^6.3.1
  google_mlkit_text_recognition: ^0.15.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
